#pragma once

#define BLOCK_SIZE 30
#define GAME_HEIGHT 20
#define GAME_WIDTH 10
#define SCREEN_WIDTH 540
#define SCREEN_HEIGHT 660
#define GAMEBOARD_WIDTH_OFFSET 210
#define GAMEBOARD_HEIGHT_OFFSET 30

#define MAX_KEYBOARD_KEYS 350

#define GB_TO_PX(x) (x * BLOCK_SIZE)
