#pragma once

#define BLOCK_SIZE 32
#define GAME_HEIGHT 20
#define GAME_WIDTH 10
#define SCREEN_WIDTH 576
#define SCREEN_HEIGHT 704
#define GAMEBOARD_WIDTH_OFFSET (7 * BLOCK_SIZE)
#define GAMEBOARD_HEIGHT_OFFSET (BLOCK_SIZE)

#define MAX_KEYBOARD_KEYS 350

#define GB_TO_PX(x) (x * BLOCK_SIZE)
